#!/usr/bin/env -S deno run -A
/**
 * Bootstrap secrets for Alteran PDS (Cloudflare Workers)
 *
 * Generates strong values for all required secrets and prints
 * `wrangler secret put ...` commands. Optionally writes a `.dev.vars`
 * file for local development.
 *
 * Usage examples:
 *   bun run scripts/setup-secrets.ts --env production --did did:web:example.com --handle user.example.com
 *   bun run scripts/setup-secrets.ts --write-dev-vars --did did:web:example.com --handle user.example.com
 *   bun run scripts/setup-secrets.ts --env staging
 */

import { webcrypto as crypto } from "node:crypto";
import { Secp256k1Keypair } from "@atproto/crypto";
import { existsSync, writeFileSync, readFileSync } from "node:fs";
import path from "node:path";

function arg(name: string, fallback?: string): string | undefined {
  const i = process.argv.findIndex(
    (a) => a === name || a.startsWith(name + "="),
  );
  if (i === -1) return fallback;
  const v = process.argv[i];
  if (v.includes("=")) return v.split("=").slice(1).join("=");
  return process.argv[i + 1] ?? fallback;
}

function hasFlag(name: string): boolean {
  return process.argv.some((a) => a === name);
}

function b64(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64");
}

function randomB64(bytes = 32): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return b64(buf);
}


async function generateRepoSigning(): Promise<{
  privateKeyHex: string;
  didKey: string;
}> {
  const kp = await Secp256k1Keypair.create({ exportable: true });
  const priv = await kp.export();
  const privateKeyHex = Array.from(priv)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
  return { privateKeyHex, didKey: kp.did() };
}

// ES256K is the default for service-auth; no separate Ed25519 generation needed.

function printHeader(title: string) {
  const line = "=".repeat(Math.max(60, title.length + 10));
  console.log(line);
  console.log(title);
  console.log(line);
}

async function main() {
  const env = (arg("--env") || "production").trim();
  const did = (arg("--did") || "did:web:example.com").trim();
  const handle = (arg("--handle") || "user.example.com").trim();
  const password = arg("--password") || randomB64(24);
  const writeDevVars = hasFlag("--write-dev-vars");
  const force = hasFlag("--force");

  const accessSecret = randomB64(32);
  const refreshSecret = randomB64(32);
  const repo = await generateRepoSigning();

  printHeader("Generated Secrets");
  console.log(`PDS_DID            = ${did}`);
  console.log(`PDS_HANDLE         = ${handle}`);
  console.log(`USER_PASSWORD      = ${password}`);
  console.log(`ACCESS_TOKEN       = ${accessSecret}`);
  console.log(`REFRESH_TOKEN      = ${refreshSecret}`);
  console.log(`REPO_SIGNING_KEY   = <secp256k1 hex, hidden>`);
  console.log(`REPO_SIGNING_DID   = ${repo.didKey}`);
  console.log();

  printHeader(`Wrangler Commands (${env})`);
  const envArg = env ? ` --env ${env}` : "";
  const cmds = [
    `wrangler secret put PDS_DID${envArg}`,
    `wrangler secret put PDS_HANDLE${envArg}`,
    `wrangler secret put USER_PASSWORD${envArg}`,
    `wrangler secret put ACCESS_TOKEN${envArg}`,
    `wrangler secret put REFRESH_TOKEN${envArg}`,
    `wrangler secret put REPO_SIGNING_KEY${envArg}`,
  ];
  console.log(cmds.join("\n"));
  console.log();
  console.log("Paste the following when prompted:");
  console.log("  PDS_DID:           " + did);
  console.log("  PDS_HANDLE:        " + handle);
  console.log("  USER_PASSWORD:     " + password);
  console.log("  ACCESS_TOKEN:      " + accessSecret);
  console.log("  REFRESH_TOKEN:     " + refreshSecret);
  console.log("  REPO_SIGNING_KEY:  " + repo.privateKeyHex);

  if (writeDevVars) {
    const target = path.resolve(".dev.vars");
    if (existsSync(target) && !force) {
      console.error(`\n.dev.vars already exists. Use --force to overwrite.`);
    } else {
      const content =
        [
          `# Generated by setup-secrets.ts on ${new Date().toISOString()}`,
          `PDS_DID=${did}`,
          `PDS_HANDLE=${handle}`,
          `USER_PASSWORD=${password}`,
          `ACCESS_TOKEN=${accessSecret}`,
          `REFRESH_TOKEN=${refreshSecret}`,
          `REPO_SIGNING_KEY=${repo.privateKeyHex}`,
          `PDS_CORS_ORIGIN=*`,
        ].join("\n") + "\n";
      writeFileSync(target, content, "utf8");
      console.log(`\nWrote ${target}`);
    }
  }

  console.log("\nDone. Next steps:");
  console.log("- Apply D1 migrations: wrangler d1 migrations apply pds");
  console.log(`- Deploy: bun run deploy${env ? ` --env ${env}` : ""}`);
}

main().catch((e) => {
  console.error(e?.stack || String(e));
  process.exit(1);
});
